# Generated by Django 2.2 on 2019-12-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W3app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='votes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
