# Generated by Django 2.2 on 2019-12-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W3app', '0002_fighter_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='Fighters/pictures/'),
        ),
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='Users/pictures/'),
        ),
    ]
