# Generated by Django 2.2 on 2019-12-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W3app', '0003_auto_20191217_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='totalvotes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
